package com.evoting.evoting.service;

import java.math.BigInteger;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.web3j.crypto.Credentials;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.methods.response.TransactionReceipt;
import org.web3j.protocol.http.HttpService;
import org.web3j.tx.gas.DefaultGasProvider;

import com.evoting.evoting.contract.Voting;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Service
@RequiredArgsConstructor
public class BlockchainService {

    @Value("${web3j.client-address}")
    private String blockchainUrl;

    @Value("${blockchain.private-key}")
    private String privateKey;

    @Value("${blockchain.contract-address}")
    private String contractAddress;

    private Web3j web3j;
    private Credentials credentials;
    private Voting contract; // Wrapper class generated by Web3j

    @PostConstruct
    public void init() {
        try {
            log.info("🔗 Connecting to Ethereum blockchain…");

            // Connect to Ganache/Testnet
            web3j = Web3j.build(new HttpService(blockchainUrl));

            // Load account using private key
            credentials = Credentials.create(privateKey);

            log.info("✅ Connected to blockchain as: {}", credentials.getAddress());

            // Load smart contract
            contract = Voting.load(
                    contractAddress,
                    web3j,
                    credentials,
                    new DefaultGasProvider()
            );

            log.info("✅ Smart Contract Loaded: {}", contractAddress);

        } catch (Exception e) {
            log.error("❌ Failed to initialize blockchain connection", e);
        }
    }

    // ✅ Send vote to blockchain
    public String castVote(String candidateName) {
        try {
            TransactionReceipt receipt = contract.castVote(candidateName).send();
            String txHash = receipt.getTransactionHash();

            log.info("✅ Vote recorded on blockchain. TxHash: {}", txHash);
            return txHash;

        } catch (Exception e) {
            log.error("❌ Blockchain transaction failed", e);
            return null;
        }
    }

    // ✅ Read vote count from blockchain
    public BigInteger getVotes(String candidateName) {
        try {
            return contract.getVotes(candidateName).send();
        } catch (Exception e) {
            log.error("❌ Unable to fetch vote count", e);
            return BigInteger.ZERO;
        }
    }

    // ✅ Check if voter already voted (optional)
    public boolean hasAlreadyVoted(String ethAddress) {
        try {
            return contract.hasVoted(ethAddress).send();
        } catch (Exception e) {
            log.error("❌ Unable to check vote status", e);
            return false;
        }
    }
}
